/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', 'system-ui', 'sans-serif'],
            },
            // Colours resolve through CSS variables so a theme is a block of
            // values rather than an edit to 86 files. Every class name in the
            // app keeps working unchanged - this replaces what the names point
            // at, not the names. src/index.css holds the values; the defaults
            // there are Tailwind's own, so the stock theme is the look the app
            // already had.
            colors: {
            // Every family the app actually uses, resolved through a
            // variable. `<alpha-value>` is what keeps `text-white/55`
            // and every other slash-opacity class working untouched.
            white: 'rgb(var(--c-white) / <alpha-value>)',
            black: 'rgb(var(--c-black) / <alpha-value>)',
            zinc: {
                50: 'rgb(var(--c-zinc-50) / <alpha-value>)',
                100: 'rgb(var(--c-zinc-100) / <alpha-value>)',
                200: 'rgb(var(--c-zinc-200) / <alpha-value>)',
                300: 'rgb(var(--c-zinc-300) / <alpha-value>)',
                400: 'rgb(var(--c-zinc-400) / <alpha-value>)',
                500: 'rgb(var(--c-zinc-500) / <alpha-value>)',
                600: 'rgb(var(--c-zinc-600) / <alpha-value>)',
                700: 'rgb(var(--c-zinc-700) / <alpha-value>)',
                800: 'rgb(var(--c-zinc-800) / <alpha-value>)',
                900: 'rgb(var(--c-zinc-900) / <alpha-value>)',
                950: 'rgb(var(--c-zinc-950) / <alpha-value>)',
            },
            slate: {
                50: 'rgb(var(--c-slate-50) / <alpha-value>)',
                100: 'rgb(var(--c-slate-100) / <alpha-value>)',
                200: 'rgb(var(--c-slate-200) / <alpha-value>)',
                300: 'rgb(var(--c-slate-300) / <alpha-value>)',
                400: 'rgb(var(--c-slate-400) / <alpha-value>)',
                500: 'rgb(var(--c-slate-500) / <alpha-value>)',
                600: 'rgb(var(--c-slate-600) / <alpha-value>)',
                700: 'rgb(var(--c-slate-700) / <alpha-value>)',
                800: 'rgb(var(--c-slate-800) / <alpha-value>)',
                900: 'rgb(var(--c-slate-900) / <alpha-value>)',
                950: 'rgb(var(--c-slate-950) / <alpha-value>)',
            },
            violet: {
                50: 'rgb(var(--c-violet-50) / <alpha-value>)',
                100: 'rgb(var(--c-violet-100) / <alpha-value>)',
                200: 'rgb(var(--c-violet-200) / <alpha-value>)',
                300: 'rgb(var(--c-violet-300) / <alpha-value>)',
                400: 'rgb(var(--c-violet-400) / <alpha-value>)',
                500: 'rgb(var(--c-violet-500) / <alpha-value>)',
                600: 'rgb(var(--c-violet-600) / <alpha-value>)',
                700: 'rgb(var(--c-violet-700) / <alpha-value>)',
                800: 'rgb(var(--c-violet-800) / <alpha-value>)',
                900: 'rgb(var(--c-violet-900) / <alpha-value>)',
                950: 'rgb(var(--c-violet-950) / <alpha-value>)',
            },
            emerald: {
                50: 'rgb(var(--c-emerald-50) / <alpha-value>)',
                100: 'rgb(var(--c-emerald-100) / <alpha-value>)',
                200: 'rgb(var(--c-emerald-200) / <alpha-value>)',
                300: 'rgb(var(--c-emerald-300) / <alpha-value>)',
                400: 'rgb(var(--c-emerald-400) / <alpha-value>)',
                500: 'rgb(var(--c-emerald-500) / <alpha-value>)',
                600: 'rgb(var(--c-emerald-600) / <alpha-value>)',
                700: 'rgb(var(--c-emerald-700) / <alpha-value>)',
                800: 'rgb(var(--c-emerald-800) / <alpha-value>)',
                900: 'rgb(var(--c-emerald-900) / <alpha-value>)',
                950: 'rgb(var(--c-emerald-950) / <alpha-value>)',
            },
            amber: {
                50: 'rgb(var(--c-amber-50) / <alpha-value>)',
                100: 'rgb(var(--c-amber-100) / <alpha-value>)',
                200: 'rgb(var(--c-amber-200) / <alpha-value>)',
                300: 'rgb(var(--c-amber-300) / <alpha-value>)',
                400: 'rgb(var(--c-amber-400) / <alpha-value>)',
                500: 'rgb(var(--c-amber-500) / <alpha-value>)',
                600: 'rgb(var(--c-amber-600) / <alpha-value>)',
                700: 'rgb(var(--c-amber-700) / <alpha-value>)',
                800: 'rgb(var(--c-amber-800) / <alpha-value>)',
                900: 'rgb(var(--c-amber-900) / <alpha-value>)',
                950: 'rgb(var(--c-amber-950) / <alpha-value>)',
            },
            cyan: {
                50: 'rgb(var(--c-cyan-50) / <alpha-value>)',
                100: 'rgb(var(--c-cyan-100) / <alpha-value>)',
                200: 'rgb(var(--c-cyan-200) / <alpha-value>)',
                300: 'rgb(var(--c-cyan-300) / <alpha-value>)',
                400: 'rgb(var(--c-cyan-400) / <alpha-value>)',
                500: 'rgb(var(--c-cyan-500) / <alpha-value>)',
                600: 'rgb(var(--c-cyan-600) / <alpha-value>)',
                700: 'rgb(var(--c-cyan-700) / <alpha-value>)',
                800: 'rgb(var(--c-cyan-800) / <alpha-value>)',
                900: 'rgb(var(--c-cyan-900) / <alpha-value>)',
                950: 'rgb(var(--c-cyan-950) / <alpha-value>)',
            },
            red: {
                50: 'rgb(var(--c-red-50) / <alpha-value>)',
                100: 'rgb(var(--c-red-100) / <alpha-value>)',
                200: 'rgb(var(--c-red-200) / <alpha-value>)',
                300: 'rgb(var(--c-red-300) / <alpha-value>)',
                400: 'rgb(var(--c-red-400) / <alpha-value>)',
                500: 'rgb(var(--c-red-500) / <alpha-value>)',
                600: 'rgb(var(--c-red-600) / <alpha-value>)',
                700: 'rgb(var(--c-red-700) / <alpha-value>)',
                800: 'rgb(var(--c-red-800) / <alpha-value>)',
                900: 'rgb(var(--c-red-900) / <alpha-value>)',
                950: 'rgb(var(--c-red-950) / <alpha-value>)',
            },
            sky: {
                50: 'rgb(var(--c-sky-50) / <alpha-value>)',
                100: 'rgb(var(--c-sky-100) / <alpha-value>)',
                200: 'rgb(var(--c-sky-200) / <alpha-value>)',
                300: 'rgb(var(--c-sky-300) / <alpha-value>)',
                400: 'rgb(var(--c-sky-400) / <alpha-value>)',
                500: 'rgb(var(--c-sky-500) / <alpha-value>)',
                600: 'rgb(var(--c-sky-600) / <alpha-value>)',
                700: 'rgb(var(--c-sky-700) / <alpha-value>)',
                800: 'rgb(var(--c-sky-800) / <alpha-value>)',
                900: 'rgb(var(--c-sky-900) / <alpha-value>)',
                950: 'rgb(var(--c-sky-950) / <alpha-value>)',
            },
            rose: {
                50: 'rgb(var(--c-rose-50) / <alpha-value>)',
                100: 'rgb(var(--c-rose-100) / <alpha-value>)',
                200: 'rgb(var(--c-rose-200) / <alpha-value>)',
                300: 'rgb(var(--c-rose-300) / <alpha-value>)',
                400: 'rgb(var(--c-rose-400) / <alpha-value>)',
                500: 'rgb(var(--c-rose-500) / <alpha-value>)',
                600: 'rgb(var(--c-rose-600) / <alpha-value>)',
                700: 'rgb(var(--c-rose-700) / <alpha-value>)',
                800: 'rgb(var(--c-rose-800) / <alpha-value>)',
                900: 'rgb(var(--c-rose-900) / <alpha-value>)',
                950: 'rgb(var(--c-rose-950) / <alpha-value>)',
            },
            blue: {
                50: 'rgb(var(--c-blue-50) / <alpha-value>)',
                100: 'rgb(var(--c-blue-100) / <alpha-value>)',
                200: 'rgb(var(--c-blue-200) / <alpha-value>)',
                300: 'rgb(var(--c-blue-300) / <alpha-value>)',
                400: 'rgb(var(--c-blue-400) / <alpha-value>)',
                500: 'rgb(var(--c-blue-500) / <alpha-value>)',
                600: 'rgb(var(--c-blue-600) / <alpha-value>)',
                700: 'rgb(var(--c-blue-700) / <alpha-value>)',
                800: 'rgb(var(--c-blue-800) / <alpha-value>)',
                900: 'rgb(var(--c-blue-900) / <alpha-value>)',
                950: 'rgb(var(--c-blue-950) / <alpha-value>)',
            },
            purple: {
                50: 'rgb(var(--c-purple-50) / <alpha-value>)',
                100: 'rgb(var(--c-purple-100) / <alpha-value>)',
                200: 'rgb(var(--c-purple-200) / <alpha-value>)',
                300: 'rgb(var(--c-purple-300) / <alpha-value>)',
                400: 'rgb(var(--c-purple-400) / <alpha-value>)',
                500: 'rgb(var(--c-purple-500) / <alpha-value>)',
                600: 'rgb(var(--c-purple-600) / <alpha-value>)',
                700: 'rgb(var(--c-purple-700) / <alpha-value>)',
                800: 'rgb(var(--c-purple-800) / <alpha-value>)',
                900: 'rgb(var(--c-purple-900) / <alpha-value>)',
                950: 'rgb(var(--c-purple-950) / <alpha-value>)',
            },
            pink: {
                50: 'rgb(var(--c-pink-50) / <alpha-value>)',
                100: 'rgb(var(--c-pink-100) / <alpha-value>)',
                200: 'rgb(var(--c-pink-200) / <alpha-value>)',
                300: 'rgb(var(--c-pink-300) / <alpha-value>)',
                400: 'rgb(var(--c-pink-400) / <alpha-value>)',
                500: 'rgb(var(--c-pink-500) / <alpha-value>)',
                600: 'rgb(var(--c-pink-600) / <alpha-value>)',
                700: 'rgb(var(--c-pink-700) / <alpha-value>)',
                800: 'rgb(var(--c-pink-800) / <alpha-value>)',
                900: 'rgb(var(--c-pink-900) / <alpha-value>)',
                950: 'rgb(var(--c-pink-950) / <alpha-value>)',
            },
            fuchsia: {
                50: 'rgb(var(--c-fuchsia-50) / <alpha-value>)',
                100: 'rgb(var(--c-fuchsia-100) / <alpha-value>)',
                200: 'rgb(var(--c-fuchsia-200) / <alpha-value>)',
                300: 'rgb(var(--c-fuchsia-300) / <alpha-value>)',
                400: 'rgb(var(--c-fuchsia-400) / <alpha-value>)',
                500: 'rgb(var(--c-fuchsia-500) / <alpha-value>)',
                600: 'rgb(var(--c-fuchsia-600) / <alpha-value>)',
                700: 'rgb(var(--c-fuchsia-700) / <alpha-value>)',
                800: 'rgb(var(--c-fuchsia-800) / <alpha-value>)',
                900: 'rgb(var(--c-fuchsia-900) / <alpha-value>)',
                950: 'rgb(var(--c-fuchsia-950) / <alpha-value>)',
            },
            },
        },
    },
    plugins: [],
}
