"""FEDDA Hub v4 backend.

Extracted fresh rather than carried: v3's `server.py` is 7800 lines and 140
endpoints, most of them for services v4 does not ship. This is phase 1 - the
endpoints the shell and one generate page actually call.

The one genuinely new endpoint is `/api/workflow/schema/{id}`. Everything the
UI renders comes from there, so a workflow reaches the app by declaring itself
in `config/workflow_api.json` rather than by someone writing a page for it.
See `descriptor.py`.
"""

import json
import logging
import os
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

import requests
from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

import descriptor
from logging_setup import setup_logging
from lora_service import LoRAService
from model_downloader import ModelDownloader
from module_service import ModuleService
from workflow_service import WorkflowService

if sys.platform == "win32":
    os.environ.setdefault("PYTHONIOENCODING", "utf-8")

ROOT_DIR = Path(__file__).parent.parent
CONFIG_DIR = ROOT_DIR / "config"
COMFY_DIR = ROOT_DIR / "ComfyUI"
OUTPUT_DIR = COMFY_DIR / "output"
COMFY_URL = os.environ.get("COMFY_URL", "http://127.0.0.1:8199")

setup_logging()          # configures the root logger; returns nothing
logger = logging.getLogger("fedda.server")

app = FastAPI(title="FEDDA Hub v4 Backend", version="4.0.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://127.0.0.1:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

workflow_service = WorkflowService(str(ROOT_DIR / "backend" / "workflows"))
module_service = ModuleService(CONFIG_DIR)
model_downloader = ModelDownloader(ROOT_DIR)
lora_service = LoRAService(ROOT_DIR)

# Read once at import. It is several megabytes and regenerated by a script, not
# by the running app, so re-reading it per request would cost a lot to learn
# nothing new. Restart the backend after regenerating it.
OBJECT_INFO = descriptor.load_object_info(str(CONFIG_DIR / "object_info.cache.json"))
if not OBJECT_INFO:
    logger.warning(
        "config/object_info.cache.json is missing or unreadable. Controls will "
        "fall back to plain text and numbers without bounds - regenerate it "
        "with: python scripts/require_nodes.py --comfy %s", COMFY_URL)


# ----------------------------------------------------------------- health

@app.get("/health")
async def health() -> Dict[str, Any]:
    return {"status": "ok", "version": "4.0.0"}


@app.get("/api/system/comfy-status")
async def comfy_status() -> Dict[str, Any]:
    try:
        response = requests.get(f"{COMFY_URL}/system_stats", timeout=1.5)
        return {"connected": response.ok, "url": COMFY_URL}
    except requests.RequestException:
        return {"connected": False, "url": COMFY_URL}


@app.get("/api/hardware/stats")
async def hardware_stats() -> Dict[str, Any]:
    """GPU and RAM, straight from ComfyUI - it already reports both."""
    try:
        response = requests.get(f"{COMFY_URL}/system_stats", timeout=2)
        response.raise_for_status()
        stats = response.json()
    except (requests.RequestException, ValueError):
        return {"available": False}

    devices = stats.get("devices") or []
    gpu = devices[0] if devices else {}
    total = gpu.get("vram_total") or 0
    free = gpu.get("vram_free") or 0
    return {
        "available": bool(devices),
        "gpu_name": gpu.get("name", ""),
        "vram_total": total,
        "vram_free": free,
        "vram_used": max(total - free, 0),
        "system": stats.get("system", {}),
    }


# --------------------------------------------------------------- settings

def _runtime_settings() -> Dict[str, Any]:
    path = CONFIG_DIR / "runtime_settings.json"
    try:
        return json.loads(path.read_text(encoding="utf-8-sig"))
    except (OSError, ValueError):
        return {}


def _save_runtime_settings(values: Dict[str, Any]) -> None:
    path = CONFIG_DIR / "runtime_settings.json"
    current = _runtime_settings()
    current.update(values)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(current, indent=2), encoding="utf-8")


class FoldersRequest(BaseModel):
    extra_models_path: Optional[str] = None
    output_path: Optional[str] = None


@app.get("/api/settings/folders")
async def get_folders() -> Dict[str, Any]:
    settings = _runtime_settings()
    return {
        "extra_models_path": settings.get("extra_models_path", ""),
        "output_path": settings.get("output_path", ""),
        "install_root": str(ROOT_DIR),
    }


@app.post("/api/settings/folders")
async def set_folders(req: FoldersRequest) -> Dict[str, Any]:
    values = {k: v for k, v in req.model_dump().items() if v is not None}
    _save_runtime_settings(values)
    return {"success": True, **values}


class SecretRequest(BaseModel):
    value: str = ""


def _secret_status(key: str) -> Dict[str, Any]:
    value = str(_runtime_settings().get(key) or "").strip()
    return {"configured": bool(value)}


@app.get("/api/settings/hf-token/status")
async def hf_token_status() -> Dict[str, Any]:
    return _secret_status("hf_token")


@app.post("/api/settings/hf-token")
async def set_hf_token(req: SecretRequest) -> Dict[str, Any]:
    _save_runtime_settings({"hf_token": req.value.strip()})
    return {"success": True, "configured": bool(req.value.strip())}


@app.get("/api/settings/civitai-key/status")
async def civitai_key_status() -> Dict[str, Any]:
    return _secret_status("civitai_key")


@app.post("/api/settings/civitai-key")
async def set_civitai_key(req: SecretRequest) -> Dict[str, Any]:
    _save_runtime_settings({"civitai_key": req.value.strip()})
    return {"success": True, "configured": bool(req.value.strip())}


# ---------------------------------------------------------------- modules

@app.get("/api/modules/install-state")
async def modules_install_state() -> Dict[str, Any]:
    """What this install actually has, which is what the UI degrades against."""
    state = module_service.get_install_state()
    return {
        "version": 1,
        "modules": module_service.list_modules(),
        **state,
    }


# --------------------------------------------------------------- workflows

def _load_graph(mapping: Dict[str, Any]) -> Dict[str, Any]:
    path = workflow_service.get_workflow_path(mapping.get("filename", ""))
    if not path:
        return {}
    try:
        with open(path, "r", encoding="utf-8-sig") as fh:
            graph = json.load(fh)
    except (OSError, ValueError):
        return {}
    if not workflow_service.is_api_format(graph):
        graph = workflow_service.convert_ui_to_api(graph)
    return graph


@app.get("/api/workflow/list")
async def list_workflows() -> Dict[str, Any]:
    mappings = workflow_service.load_mapping()
    items = []
    for workflow_id, mapping in mappings.items():
        if workflow_id.startswith("_"):
            continue  # `_note` and friends are documentation, not workflows
        items.append({
            "id": workflow_id,
            "name": mapping.get("name", workflow_id),
            "description": mapping.get("description", ""),
            "module": mapping.get("module", ""),
            "available": module_service.is_workflow_available(workflow_id).get("available", True),
        })
    return {"workflows": items}


@app.get("/api/workflow/schema/{workflow_id}")
async def workflow_schema(workflow_id: str) -> Dict[str, Any]:
    """The controls this workflow needs, and what kind each one is.

    This is the whole reason v4 has one generate page instead of sixty-one.
    """
    mapping = workflow_service.load_mapping().get(workflow_id)
    if not mapping:
        raise HTTPException(status_code=404, detail=f"unknown workflow '{workflow_id}'")
    graph = _load_graph(mapping)
    return descriptor.describe_workflow(workflow_id, mapping, graph, OBJECT_INFO)


@app.get("/api/workflow/model-status/{workflow_id}")
async def workflow_model_status(workflow_id: str) -> Dict[str, Any]:
    """Which of this workflow's models are already on disk.

    `model_downloader` answers it, and it looks in the user's own library as
    well as the install's tree - the fix that stopped a machine with the models
    already attached from refusing to generate and re-downloading them.
    """
    module = module_service.module_for_workflow(workflow_id) or {}
    required = module.get("models") or []
    if not required:
        return {"ready": True, "files": []}
    return model_downloader.ensure_zimage_core_models(required)


@app.post("/api/workflow/download-models/{workflow_id}")
async def workflow_download_models(workflow_id: str) -> Dict[str, Any]:
    module = module_service.module_for_workflow(workflow_id) or {}
    required = module.get("models") or []
    return model_downloader.ensure_zimage_core_models(required)


@app.get("/api/models/status/{filename}")
async def model_status(filename: str) -> Dict[str, Any]:
    return model_downloader.get_progress(filename)


# ---------------------------------------------------------------- generate

class GenerateRequest(BaseModel):
    workflow_id: str
    params: Dict[str, Any] = {}


@app.post("/api/generate")
async def generate(req: GenerateRequest) -> Dict[str, Any]:
    availability = module_service.is_workflow_available(req.workflow_id)
    if not availability.get("available", True):
        raise HTTPException(
            status_code=403,
            detail=availability.get("detail")
            or f"'{req.workflow_id}' is not installed on this machine",
        )

    payload = workflow_service.prepare_payload(req.workflow_id, req.params)
    if not payload:
        raise HTTPException(status_code=400,
                            detail=f"Could not build a graph for '{req.workflow_id}'")

    try:
        submit = requests.post(
            f"{COMFY_URL}/prompt",
            json={"prompt": payload, "client_id": "fedda_v4"},
            timeout=20,
        )
    except requests.RequestException as exc:
        raise HTTPException(status_code=503,
                            detail=f"ComfyUI is not answering on {COMFY_URL}: {exc}")

    if not submit.ok:
        # ComfyUI's own rejection is far more useful than a generic 500 - it
        # names the node and the input it refused.
        raise HTTPException(status_code=400, detail=f"ComfyUI refused the graph: {submit.text}")

    prompt_id = submit.json().get("prompt_id")
    if not prompt_id:
        raise HTTPException(status_code=502, detail="ComfyUI returned no prompt_id")

    logger.info("queued %s as %s", req.workflow_id, prompt_id)
    return {"success": True, "prompt_id": prompt_id}


@app.post("/api/generate/cancel")
async def cancel_generation() -> Dict[str, Any]:
    try:
        requests.post(f"{COMFY_URL}/interrupt", timeout=5)
        return {"success": True}
    except requests.RequestException as exc:
        return {"success": False, "detail": str(exc)}


def _outputs_from_history(entry: Dict[str, Any]) -> List[str]:
    """Every image the run wrote, as URLs the frontend can load."""
    urls: List[str] = []
    for node_output in (entry.get("outputs") or {}).values():
        for item in (node_output.get("images") or []):
            filename = item.get("filename")
            if not filename:
                continue
            urls.append(
                f"{COMFY_URL}/view?filename={filename}"
                f"&subfolder={item.get('subfolder', '')}"
                f"&type={item.get('type', 'output')}"
            )
    return urls


@app.get("/api/generate/status/{prompt_id}")
async def generation_status(prompt_id: str, workflow_id: str = "") -> Dict[str, Any]:
    try:
        response = requests.get(f"{COMFY_URL}/history/{prompt_id}", timeout=10)
        history = response.json() if response.ok else {}
    except (requests.RequestException, ValueError):
        return {"status": "running"}

    entry = history.get(prompt_id)
    if not entry:
        # Not in history yet means queued or executing, not lost.
        return {"status": "running"}

    status = (entry.get("status") or {})
    if status.get("status_str") == "error":
        messages = status.get("messages") or []
        return {"status": "failed", "detail": str(messages[-1]) if messages else "ComfyUI reported an error"}

    images = _outputs_from_history(entry)
    if status.get("completed") or images:
        return {"status": "completed", "images": images, "prompt_id": prompt_id}
    return {"status": "running"}


# ------------------------------------------------------------------ upload

# ComfyUI resolves a workflow's `image` input against its own input folder, so
# an upload is a copy into that folder and the filename it answers with. The
# app never keeps its own copy: two folders holding the same picture is how the
# two disagree later.
_UPLOAD_MAX_BYTES = 64 * 1024 * 1024
_UPLOAD_TYPES = ("image/", "video/", "audio/")


@app.post("/api/upload")
async def upload(file: UploadFile = File(...)) -> Dict[str, Any]:
    """Put a file where ComfyUI can find it, and return the name it gave it."""
    content_type = str(file.content_type or "")
    if content_type and not content_type.startswith(_UPLOAD_TYPES):
        raise HTTPException(status_code=415,
                            detail=f"{content_type} is not an image, video or audio file")

    content = await file.read()
    if not content:
        raise HTTPException(status_code=400, detail="The file was empty")
    # Read first, then check. FastAPI spools a large upload to disk rather than
    # holding it in memory, so the cap is about what ComfyUI is asked to store,
    # not about surviving the request.
    if len(content) > _UPLOAD_MAX_BYTES:
        raise HTTPException(
            status_code=413,
            detail=f"{len(content) // (1024 * 1024)} MB is over the "
                   f"{_UPLOAD_MAX_BYTES // (1024 * 1024)} MB limit")

    try:
        response = requests.post(
            f"{COMFY_URL}/upload/image",
            files={"image": (file.filename, content,
                            content_type or "application/octet-stream")},
            # An upload competes with whatever ComfyUI is rendering, and a 4K
            # frame over a busy event loop is not a five-second operation.
            timeout=180,
        )
    except requests.RequestException as exc:
        raise HTTPException(status_code=503,
                            detail=f"ComfyUI is not answering on {COMFY_URL}: {exc}")

    if not response.ok:
        raise HTTPException(status_code=502,
                            detail=f"ComfyUI refused the upload: {response.text}")

    data = response.json()
    # ComfyUI renames on collision - image.png becomes image (2).png - so the
    # name it answers with is the one the graph must reference, never the one
    # that was sent. A subfolder comes back when it stored one; the graph slot
    # takes the two joined.
    name = data.get("name") or file.filename
    subfolder = str(data.get("subfolder") or "")
    logger.info("uploaded %s as %s", file.filename, name)
    return {
        "success": True,
        "filename": f"{subfolder}/{name}" if subfolder else name,
        "name": name,
        "subfolder": subfolder,
        "url": f"{COMFY_URL}/view?filename={name}&subfolder={subfolder}&type=input",
    }


# -------------------------------------------------------------------- LoRA

@app.get("/api/lora/list")
async def lora_list() -> Dict[str, Any]:
    """Every LoRA a workflow can reference.

    `list_lora_names` asks ComfyUI rather than scanning a folder, which is what
    makes a library on another drive show up. Scanning `ComfyUI/models/loras`
    directly - v3 did this in one place - reports none of it.
    """
    return {"loras": lora_service.list_lora_names()}


@app.get("/api/lora/installed")
async def lora_installed() -> Dict[str, Any]:
    return {"installed": lora_service.get_installed()}


# ------------------------------------------------------------------- files

@app.get("/api/files/list")
async def files_list(limit: int = 100) -> Dict[str, Any]:
    """Recent output files, newest first."""
    if not OUTPUT_DIR.exists():
        return {"files": []}
    allowed = {".png", ".jpg", ".jpeg", ".webp", ".mp4", ".webm"}
    found = [p for p in OUTPUT_DIR.rglob("*")
             if p.is_file() and p.suffix.lower() in allowed]
    found.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    files = []
    for path in found[:limit]:
        rel = path.relative_to(OUTPUT_DIR).as_posix()
        subfolder = str(Path(rel).parent).replace("\\", "/")
        files.append({
            "filename": path.name,
            "subfolder": "" if subfolder == "." else subfolder,
            "modified": path.stat().st_mtime,
            "size": path.stat().st_size,
            "url": f"{COMFY_URL}/view?filename={path.name}"
                   f"&subfolder={'' if subfolder == '.' else subfolder}&type=output",
        })
    return {"files": files}


class DeleteRequest(BaseModel):
    filename: str
    subfolder: str = ""


@app.post("/api/files/delete")
async def files_delete(req: DeleteRequest) -> Dict[str, Any]:
    # Resolve inside the output tree and check afterwards, so a filename
    # carrying `..` cannot walk out of it.
    target = (OUTPUT_DIR / req.subfolder / req.filename).resolve()
    if not str(target).startswith(str(OUTPUT_DIR.resolve())):
        raise HTTPException(status_code=400, detail="Path outside the output folder")
    if not target.is_file():
        raise HTTPException(status_code=404, detail="No such file")
    target.unlink()
    return {"success": True}


# ------------------------------------------------------------------ ComfyUI

@app.post("/api/comfy/restart")
async def comfy_restart() -> Dict[str, Any]:
    """Ask ComfyUI to shut down; `run.ps1` brings it back up."""
    try:
        requests.post(f"{COMFY_URL}/shutdown", timeout=5)
    except requests.RequestException:
        pass  # a shutdown that closes the socket looks like a failed request
    for _ in range(20):
        time.sleep(0.5)
        try:
            requests.get(f"{COMFY_URL}/system_stats", timeout=1)
            return {"success": True, "restarted": True}
        except requests.RequestException:
            continue
    return {"success": True, "restarted": False,
            "detail": "ComfyUI stopped; it may still be starting"}


@app.post("/api/comfy/refresh-models")
async def comfy_refresh_models() -> Dict[str, Any]:
    lora_service.refresh_cache()
    try:
        response = requests.post(f"{COMFY_URL}/api/models/refresh", timeout=10)
        return {"success": response.ok}
    except requests.RequestException as exc:
        return {"success": False, "detail": str(exc)}


if __name__ == "__main__":
    import uvicorn

    # No reload. It doubles the process, and `object_info.cache.json` is read
    # once at import - a reloader would load several megabytes twice per edit.
    print("[FEDDA Hub v4] backend on http://127.0.0.1:8000")
    uvicorn.run(app, host="127.0.0.1", port=8000, log_level="info")
