"""FEDDA Hub v4 backend.

Extracted fresh rather than carried: v3's `server.py` is 7800 lines and 140
endpoints, most of them for services v4 does not ship. This is phase 1 - the
endpoints the shell and one generate page actually call.

The one genuinely new endpoint is `/api/workflow/schema/{id}`. Everything the
UI renders comes from there, so a workflow reaches the app by declaring itself
in `config/workflow_api.json` rather than by someone writing a page for it.
See `descriptor.py`.
"""

import json
import logging
import os
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

import requests
from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# This directory has to be on sys.path before the sibling imports below.
#
# Normally Python prepends a script's own directory and none of this is
# needed - but the app runs on the embedded distribution, whose
# python311._pth replaces sys.path outright and does not include it. So
# `import descriptor` fails at startup with ModuleNotFoundError, the backend
# never binds port 8000, and the UI loads with every module missing rather
# than with an error that names the cause.
#
# v3 carried these three lines for the same reason. Writing this file fresh
# lost them, and the in-process tests hid it by putting backend/ on the path
# themselves - so it passed everywhere except where it runs.
_backend_dir = os.path.dirname(os.path.abspath(__file__))
if _backend_dir not in sys.path:
    sys.path.insert(0, _backend_dir)

import descriptor
import encoders
import model_links
from logging_setup import setup_logging
from lora_service import LoRAService
from model_downloader import ModelDownloader
from module_service import ModuleService
from workflow_service import WorkflowService

if sys.platform == "win32":
    os.environ.setdefault("PYTHONIOENCODING", "utf-8")

ROOT_DIR = Path(__file__).parent.parent
CONFIG_DIR = ROOT_DIR / "config"
COMFY_DIR = ROOT_DIR / "ComfyUI"
OUTPUT_DIR = COMFY_DIR / "output"
COMFY_URL = os.environ.get("COMFY_URL", "http://127.0.0.1:8199")

setup_logging()          # configures the root logger; returns nothing
logger = logging.getLogger("fedda.server")

app = FastAPI(title="FEDDA Hub v4 Backend", version="4.0.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://127.0.0.1:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

workflow_service = WorkflowService(str(ROOT_DIR / "backend" / "workflows"))
module_service = ModuleService(CONFIG_DIR)
model_downloader = ModelDownloader(ROOT_DIR)
lora_service = LoRAService(ROOT_DIR)

# Read once at import. It is several megabytes and regenerated by a script, not
# by the running app, so re-reading it per request would cost a lot to learn
# nothing new. Restart the backend after regenerating it.
OBJECT_INFO = descriptor.load_object_info(str(CONFIG_DIR / "object_info.cache.json"))
if not OBJECT_INFO:
    logger.warning(
        "config/object_info.cache.json is missing or unreadable. Controls will "
        "fall back to plain text and numbers without bounds - regenerate it "
        "with: python scripts/require_nodes.py --comfy %s", COMFY_URL)


# ----------------------------------------------------------------- health

@app.get("/health")
async def health() -> Dict[str, Any]:
    return {"status": "ok", "version": "4.0.0"}


@app.get("/api/system/comfy-status")
async def comfy_status() -> Dict[str, Any]:
    try:
        response = requests.get(f"{COMFY_URL}/system_stats", timeout=1.5)
        return {"connected": response.ok, "url": COMFY_URL}
    except requests.RequestException:
        return {"connected": False, "url": COMFY_URL}


@app.get("/api/hardware/stats")
async def hardware_stats() -> Dict[str, Any]:
    """GPU and RAM, straight from ComfyUI - it already reports both."""
    try:
        response = requests.get(f"{COMFY_URL}/system_stats", timeout=2)
        response.raise_for_status()
        stats = response.json()
    except (requests.RequestException, ValueError):
        return {"available": False}

    devices = stats.get("devices") or []
    gpu = devices[0] if devices else {}
    total = gpu.get("vram_total") or 0
    free = gpu.get("vram_free") or 0
    return {
        "available": bool(devices),
        "gpu_name": gpu.get("name", ""),
        "vram_total": total,
        "vram_free": free,
        "vram_used": max(total - free, 0),
        "system": stats.get("system", {}),
    }


# --------------------------------------------------------------- settings

def _runtime_settings() -> Dict[str, Any]:
    path = CONFIG_DIR / "runtime_settings.json"
    try:
        return json.loads(path.read_text(encoding="utf-8-sig"))
    except (OSError, ValueError):
        return {}


def _save_runtime_settings(values: Dict[str, Any]) -> None:
    path = CONFIG_DIR / "runtime_settings.json"
    current = _runtime_settings()
    current.update(values)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(current, indent=2), encoding="utf-8")


class FoldersRequest(BaseModel):
    extra_models_path: str = ""
    output_path: str = ""
    input_path: str = ""


def _folder_defaults() -> Dict[str, str]:
    """What each folder is when the user has not chosen one."""
    return {
        "extra_models_path": "",
        "output_path": str(ROOT_DIR / "ComfyUI" / "output"),
        "input_path": str(ROOT_DIR / "ComfyUI" / "input"),
    }


def _check_folder(label: str, raw_value: str, needs_write: bool) -> str:
    """Validate one path, or raise with something the user can act on.

    Checked on the way in rather than on the way out. A bad path saved here
    does not fail until a generate reaches for it, by which point the error
    surfaces as a broken render rather than as a folder someone mistyped.
    """
    value = (raw_value or "").strip().strip('"')
    if not value:
        return ""
    path = Path(value)
    if not path.exists():
        raise HTTPException(status_code=400, detail=f"{label}: {value} does not exist")
    if not path.is_dir():
        raise HTTPException(status_code=400, detail=f"{label}: {value} is not a folder")
    if needs_write:
        probe = path / ".fedda_write_test"
        try:
            probe.write_text("", encoding="utf-8")
            probe.unlink()
        except OSError:
            raise HTTPException(status_code=400,
                                detail=f"{label}: cannot write to {value}")
    return str(path)


@app.get("/api/settings/folders")
async def get_folders() -> Dict[str, Any]:
    settings = _runtime_settings()
    defaults = _folder_defaults()
    return {
        "success": True,
        "paths": {key: str(settings.get(key) or "").strip() for key in defaults},
        "defaults": defaults,
        # Every one of these is read at startup, so nothing changes until
        # FEDDA restarts. The dialog says so rather than implying otherwise.
        "requires_restart": True,
    }


@app.post("/api/settings/folders")
async def set_folders(req: FoldersRequest) -> Dict[str, Any]:
    extra = _check_folder("Extra models", req.extra_models_path, needs_write=False)
    output = _check_folder("Output", req.output_path, needs_write=True)
    inp = _check_folder("Input", req.input_path, needs_write=True)

    # An extra models tree that is really FEDDA's own is not an extra tree,
    # and listing it twice would make ComfyUI resolve every model through two
    # identical roots.
    own_models = (ROOT_DIR / "ComfyUI" / "models").resolve()
    if extra and Path(extra).resolve() == own_models:
        raise HTTPException(
            status_code=400,
            detail="Extra models: that is FEDDA's own models folder, which is already used")

    paths = {"extra_models_path": extra, "output_path": output, "input_path": inp}
    _save_runtime_settings(paths)
    return {"success": True, "paths": paths, "requires_restart": True}


class SecretRequest(BaseModel):
    value: str = ""


def _secret_status(key: str) -> Dict[str, Any]:
    value = str(_runtime_settings().get(key) or "").strip()
    return {"configured": bool(value)}


@app.get("/api/settings/hf-token/status")
async def hf_token_status() -> Dict[str, Any]:
    return _secret_status("hf_token")


@app.post("/api/settings/hf-token")
async def set_hf_token(req: SecretRequest) -> Dict[str, Any]:
    _save_runtime_settings({"hf_token": req.value.strip()})
    return {"success": True, "configured": bool(req.value.strip())}


@app.get("/api/settings/civitai-key/status")
async def civitai_key_status() -> Dict[str, Any]:
    return _secret_status("civitai_key")


@app.post("/api/settings/civitai-key")
async def set_civitai_key(req: SecretRequest) -> Dict[str, Any]:
    _save_runtime_settings({"civitai_key": req.value.strip()})
    return {"success": True, "configured": bool(req.value.strip())}


# ---------------------------------------------------------------- modules

@app.get("/api/modules/install-state")
async def modules_install_state() -> Dict[str, Any]:
    """What this install actually has, which is what the UI degrades against."""
    state = module_service.get_install_state()
    return {
        "version": 1,
        "modules": module_service.list_modules(),
        **state,
    }


# --------------------------------------------------------------- workflows

def _load_graph(mapping: Dict[str, Any]) -> Dict[str, Any]:
    path = workflow_service.get_workflow_path(mapping.get("filename", ""))
    if not path:
        return {}
    try:
        with open(path, "r", encoding="utf-8-sig") as fh:
            graph = json.load(fh)
    except (OSError, ValueError):
        return {}
    if not workflow_service.is_api_format(graph):
        graph = workflow_service.convert_ui_to_api(graph)
    return graph


@app.get("/api/workflow/list")
async def list_workflows() -> Dict[str, Any]:
    mappings = workflow_service.load_mapping()
    items = []
    for workflow_id, mapping in mappings.items():
        if workflow_id.startswith("_"):
            continue  # `_note` and friends are documentation, not workflows
        items.append({
            "id": workflow_id,
            "name": mapping.get("name", workflow_id),
            "description": mapping.get("description", ""),
            "module": mapping.get("module", ""),
            "available": module_service.is_workflow_available(workflow_id).get("available", True),
        })
    return {"workflows": items}


@app.get("/api/workflow/schema/{workflow_id}")
async def workflow_schema(workflow_id: str) -> Dict[str, Any]:
    """The controls this workflow needs, and what kind each one is.

    This is the whole reason v4 has one generate page instead of sixty-one.
    """
    mapping = workflow_service.load_mapping().get(workflow_id)
    if not mapping:
        raise HTTPException(status_code=404, detail=f"unknown workflow '{workflow_id}'")
    graph = _load_graph(mapping)
    return descriptor.describe_workflow(workflow_id, mapping, graph, OBJECT_INFO)


def _workflow_models(workflow_id: str) -> List[Dict[str, Any]]:
    """Every model this workflow needs, and where each one already is.

    Two sources, unioned by filename. `modules.json` names the files a module
    needs and `model_downloader` holds their URLs; a graph may also declare
    its own downloads inline through a HuggingFaceDownloader node. Today the
    first supplies everything and the second is empty for all six workflows -
    which is why reading only the graph, as the first version of this did,
    reported nothing to download while the wire was saturated.
    """
    extra = str(_runtime_settings().get("extra_models_path") or "")
    mapping = workflow_service.load_mapping().get(workflow_id)
    if not mapping:
        return []
    path = workflow_service.get_workflow_path(mapping.get("filename", ""))
    if not path:
        return []
    graph = model_links.load_graph(path)

    files: List[Dict[str, Any]] = []
    seen = set()

    for item in model_links.models_from_graph(graph):
        name = item["filename"]
        seen.add(name.lower())
        spec = model_downloader.zimage_core_specs.get(name)
        # Not every spec places its file by folder: some carry a
        # root_relative_path instead, and reading relative_dir off those
        # raises rather than falling back.
        folder = item["folder"]
        if spec and spec.get("relative_dir"):
            folder = str(spec["relative_dir"]).replace("\\", "/")

        # The spec knows the exact folder, so ask there first and only walk
        # the tree for files it does not place.
        found = (model_links.find_existing_model(folder, name, ROOT_DIR, extra)
                 if folder else None)
        if found is None:
            found = model_links.find_anywhere(name, ROOT_DIR, extra)

        files.append({
            "filename": name,
            "folder": folder,
            "url": str(spec["url"]) if spec else "",
            "path": (str(model_downloader._dest_path_for_spec(spec, name))
                     if spec else ""),
            "exists": found is not None,
            "size_bytes": found.stat().st_size if found else 0,
            # Named by the workflow with nowhere to fetch it from. Reported
            # rather than dropped: a model the app cannot get is something
            # the user has to know about, not something to hide. Several are
            # fetched by the node pack itself on first use.
            **({} if spec else {"no_source": True}),
        })

    # A graph may also declare downloads inline through a
    # HuggingFaceDownloader node. None of the six do today.
    for item in model_links.parse_download_links(graph, ROOT_DIR, extra):
        if item["filename"].lower() not in seen:
            files.append(item)
            seen.add(item["filename"].lower())

    return files


@app.get("/api/workflow/model-status/{workflow_id}")
async def workflow_model_status(workflow_id: str) -> Dict[str, Any]:
    """Which of this workflow's models this machine already has.

    Read off the graph rather than from a list in modules.json: the
    HuggingFaceDownloader node carries the URLs, so a workflow states its own
    requirements and adopting one does not mean maintaining an inventory
    beside it.

    "Already has" means anywhere ComfyUI will look, which includes the folder
    Settings points at. Asking only about our own tree is what once made an
    install with the models already attached refuse to generate and start
    re-downloading twenty gigabytes it had.
    """
    files = _workflow_models(workflow_id)
    return {"files": files, "ready": all(f["exists"] for f in files)}


@app.get("/api/workflow/download-live-progress/{workflow_id}")
async def workflow_download_live_progress(workflow_id: str) -> Dict[str, Any]:
    """Bytes on disk against bytes expected, polled while a download runs.

    This is what the banner draws. Without it the transfer ran at full speed
    with nothing on screen at all - the endpoint the UI polls simply was not
    there, and a 404 every two seconds looks exactly like an idle app.
    """
    token = str(_runtime_settings().get("hf_token") or "").strip()
    return {"files": model_links.live_progress(_workflow_models(workflow_id), token)}


@app.post("/api/workflow/download-models/{workflow_id}")
async def workflow_download_models(workflow_id: str) -> Dict[str, Any]:
    """Fetch everything missing, without running the workflow."""
    files = _workflow_models(workflow_id)
    if not files:
        raise HTTPException(status_code=404,
                            detail=f"No models declared by '{workflow_id}'")

    token = str(_runtime_settings().get("hf_token") or "").strip()
    started, already = [], []
    for item in files:
        if item["exists"]:
            already.append(item["filename"])
            continue
        if not item.get("url"):
            continue  # named by the module, but nothing knows where to get it
        # The token goes only to Hugging Face. Sending it to a mirror or a
        # CDN would hand someone else the user's credential.
        headers = ({"Authorization": f"Bearer {token}"}
                   if token and "huggingface.co" in item["url"] else None)
        dest = Path(item["path"])
        dest.parent.mkdir(parents=True, exist_ok=True)
        model_downloader.start_url_download(
            item["url"], dest, item["filename"], headers=headers)
        started.append(item["filename"])

    logger.info("download %s: %d starting, %d already here",
                workflow_id, len(started), len(already))
    return {"success": True, "started": started, "already_present": already}


@app.get("/api/models/status/{filename}")
async def model_status(filename: str) -> Dict[str, Any]:
    return model_downloader.get_progress(filename)


# ---------------------------------------------------------------- generate

class GenerateRequest(BaseModel):
    workflow_id: str
    params: Dict[str, Any] = {}
    # Whose websocket should hear about this run.
    #
    # ComfyUI addresses its execution messages - progress, previews, and the
    # `executed` event carrying the finished filenames - to the client_id that
    # submitted the prompt. This used to be hardcoded to "fedda_v4", a name no
    # socket was ever registered under, so every one of those messages was
    # delivered to nobody: no progress bar, no live preview, and a Recent
    # Generations strip that stayed empty however many pictures were made.
    #
    # The browser opens its own socket as `fedda_web_...` and now sends that
    # name here. The old constant remains the fallback, for a caller that has
    # no socket of its own and does not need to be told anything.
    client_id: str = "fedda_v4"


@app.post("/api/generate")
async def generate(req: GenerateRequest) -> Dict[str, Any]:
    availability = module_service.is_workflow_available(req.workflow_id)
    if not availability.get("available", True):
        raise HTTPException(
            status_code=403,
            detail=availability.get("detail")
            or f"'{req.workflow_id}' is not installed on this machine",
        )

    # A few nodes want their value in a shape the control cannot produce -
    # Pixaroma packs a prompt into a hidden JSON string, for one. The mapping
    # names an encoder for those; everything else passes through untouched.
    mapping = workflow_service.load_mapping().get(req.workflow_id) or {}

    # An unfilled upload used to reach ComfyUI as an empty string, and LoadImage
    # would try to open the input *directory* as a file: "Permission denied:
    # ...\ComfyUI\input", from av.error, several nodes into the run. The
    # cause is not in that message anywhere.
    #
    # Same shape as the empty-string-over-a-number bug descriptor.py records:
    # a control that was never filled must not overwrite the graph, and here it
    # must not start the run at all - there is no sensible picture to fall back
    # on.
    graph_desc = descriptor.describe_workflow(
        req.workflow_id, mapping, _load_graph(mapping), OBJECT_INFO)
    missing = [f["label"] for f in graph_desc["fields"]
               if f.get("required") and not str(req.params.get(f["key"]) or "").strip()]
    if missing:
        raise HTTPException(
            status_code=400,
            detail="Fill these in first: %s" % ", ".join(missing))

    params = encoders.apply(mapping, req.params)

    payload = workflow_service.prepare_payload(req.workflow_id, params)
    if not payload:
        raise HTTPException(status_code=400,
                            detail=f"Could not build a graph for '{req.workflow_id}'")

    try:
        submit = requests.post(
            f"{COMFY_URL}/prompt",
            json={"prompt": payload, "client_id": req.client_id},
            timeout=20,
        )
    except requests.RequestException as exc:
        raise HTTPException(status_code=503,
                            detail=f"ComfyUI is not answering on {COMFY_URL}: {exc}")

    if not submit.ok:
        # ComfyUI's own rejection is far more useful than a generic 500 - it
        # names the node and the input it refused.
        raise HTTPException(status_code=400, detail=f"ComfyUI refused the graph: {submit.text}")

    prompt_id = submit.json().get("prompt_id")
    if not prompt_id:
        raise HTTPException(status_code=502, detail="ComfyUI returned no prompt_id")

    logger.info("queued %s as %s", req.workflow_id, prompt_id)
    return {"success": True, "prompt_id": prompt_id}


@app.post("/api/generate/cancel")
async def cancel_generation() -> Dict[str, Any]:
    try:
        requests.post(f"{COMFY_URL}/interrupt", timeout=5)
        return {"success": True}
    except requests.RequestException as exc:
        return {"success": False, "detail": str(exc)}


def _outputs_from_history(entry: Dict[str, Any]) -> List[str]:
    """Every image the run wrote, as URLs the frontend can load."""
    urls: List[str] = []
    for node_output in (entry.get("outputs") or {}).values():
        for item in (node_output.get("images") or []):
            filename = item.get("filename")
            if not filename:
                continue
            urls.append(
                f"{COMFY_URL}/view?filename={filename}"
                f"&subfolder={item.get('subfolder', '')}"
                f"&type={item.get('type', 'output')}"
            )
    return urls


@app.get("/api/generate/status/{prompt_id}")
async def generation_status(prompt_id: str, workflow_id: str = "") -> Dict[str, Any]:
    try:
        response = requests.get(f"{COMFY_URL}/history/{prompt_id}", timeout=10)
        history = response.json() if response.ok else {}
    except (requests.RequestException, ValueError):
        return {"status": "running"}

    entry = history.get(prompt_id)
    if not entry:
        # Not in history yet means queued or executing, not lost.
        return {"status": "running"}

    status = (entry.get("status") or {})
    if status.get("status_str") == "error":
        messages = status.get("messages") or []
        return {"status": "failed", "detail": str(messages[-1]) if messages else "ComfyUI reported an error"}

    images = _outputs_from_history(entry)
    if status.get("completed") or images:
        return {"status": "completed", "images": images, "prompt_id": prompt_id}
    return {"status": "running"}


# ------------------------------------------------------------------ upload

# ComfyUI resolves a workflow's `image` input against its own input folder, so
# an upload is a copy into that folder and the filename it answers with. The
# app never keeps its own copy: two folders holding the same picture is how the
# two disagree later.
_UPLOAD_MAX_BYTES = 64 * 1024 * 1024
_UPLOAD_TYPES = ("image/", "video/", "audio/")


@app.post("/api/upload")
async def upload(file: UploadFile = File(...)) -> Dict[str, Any]:
    """Put a file where ComfyUI can find it, and return the name it gave it."""
    content_type = str(file.content_type or "")
    if content_type and not content_type.startswith(_UPLOAD_TYPES):
        raise HTTPException(status_code=415,
                            detail=f"{content_type} is not an image, video or audio file")

    content = await file.read()
    if not content:
        raise HTTPException(status_code=400, detail="The file was empty")
    # Read first, then check. FastAPI spools a large upload to disk rather than
    # holding it in memory, so the cap is about what ComfyUI is asked to store,
    # not about surviving the request.
    if len(content) > _UPLOAD_MAX_BYTES:
        raise HTTPException(
            status_code=413,
            detail=f"{len(content) // (1024 * 1024)} MB is over the "
                   f"{_UPLOAD_MAX_BYTES // (1024 * 1024)} MB limit")

    try:
        response = requests.post(
            f"{COMFY_URL}/upload/image",
            files={"image": (file.filename, content,
                            content_type or "application/octet-stream")},
            # An upload competes with whatever ComfyUI is rendering, and a 4K
            # frame over a busy event loop is not a five-second operation.
            timeout=180,
        )
    except requests.RequestException as exc:
        raise HTTPException(status_code=503,
                            detail=f"ComfyUI is not answering on {COMFY_URL}: {exc}")

    if not response.ok:
        raise HTTPException(status_code=502,
                            detail=f"ComfyUI refused the upload: {response.text}")

    data = response.json()
    # ComfyUI renames on collision - image.png becomes image (2).png - so the
    # name it answers with is the one the graph must reference, never the one
    # that was sent. A subfolder comes back when it stored one; the graph slot
    # takes the two joined.
    name = data.get("name") or file.filename
    subfolder = str(data.get("subfolder") or "")
    logger.info("uploaded %s as %s", file.filename, name)
    return {
        "success": True,
        "filename": f"{subfolder}/{name}" if subfolder else name,
        "name": name,
        "subfolder": subfolder,
        "url": f"{COMFY_URL}/view?filename={name}&subfolder={subfolder}&type=input",
    }


# -------------------------------------------------------------------- LoRA

@app.get("/api/lora/list")
async def lora_list() -> Dict[str, Any]:
    """Every LoRA a workflow can reference.

    `list_lora_names` asks ComfyUI rather than scanning a folder, which is what
    makes a library on another drive show up. Scanning `ComfyUI/models/loras`
    directly - v3 did this in one place - reports none of it.
    """
    return {"loras": lora_service.list_lora_names()}


@app.get("/api/lora/installed")
async def lora_installed() -> Dict[str, Any]:
    return {"installed": lora_service.get_installed()}


# ------------------------------------------------------------------- files

@app.get("/api/files/list")
async def files_list(limit: int = 100) -> Dict[str, Any]:
    """Recent output files, newest first."""
    if not OUTPUT_DIR.exists():
        return {"files": []}
    allowed = {".png", ".jpg", ".jpeg", ".webp", ".mp4", ".webm"}
    found = [p for p in OUTPUT_DIR.rglob("*")
             if p.is_file() and p.suffix.lower() in allowed]
    found.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    files = []
    for path in found[:limit]:
        rel = path.relative_to(OUTPUT_DIR).as_posix()
        subfolder = str(Path(rel).parent).replace("\\", "/")
        files.append({
            "filename": path.name,
            "subfolder": "" if subfolder == "." else subfolder,
            "modified": path.stat().st_mtime,
            "size": path.stat().st_size,
            "url": f"{COMFY_URL}/view?filename={path.name}"
                   f"&subfolder={'' if subfolder == '.' else subfolder}&type=output",
        })
    return {"files": files}


class DeleteRequest(BaseModel):
    filename: str
    subfolder: str = ""


@app.post("/api/files/delete")
async def files_delete(req: DeleteRequest) -> Dict[str, Any]:
    # Resolve inside the output tree and check afterwards, so a filename
    # carrying `..` cannot walk out of it.
    target = (OUTPUT_DIR / req.subfolder / req.filename).resolve()
    if not str(target).startswith(str(OUTPUT_DIR.resolve())):
        raise HTTPException(status_code=400, detail="Path outside the output folder")
    if not target.is_file():
        raise HTTPException(status_code=404, detail="No such file")
    target.unlink()
    return {"success": True}


# ------------------------------------------------------------------ ComfyUI

@app.post("/api/comfy/restart")
async def comfy_restart() -> Dict[str, Any]:
    """Ask ComfyUI to shut down; `run.ps1` brings it back up."""
    try:
        requests.post(f"{COMFY_URL}/shutdown", timeout=5)
    except requests.RequestException:
        pass  # a shutdown that closes the socket looks like a failed request
    for _ in range(20):
        time.sleep(0.5)
        try:
            requests.get(f"{COMFY_URL}/system_stats", timeout=1)
            return {"success": True, "restarted": True}
        except requests.RequestException:
            continue
    return {"success": True, "restarted": False,
            "detail": "ComfyUI stopped; it may still be starting"}


@app.post("/api/comfy/refresh-models")
async def comfy_refresh_models() -> Dict[str, Any]:
    lora_service.refresh_cache()
    try:
        response = requests.post(f"{COMFY_URL}/api/models/refresh", timeout=10)
        return {"success": response.ok}
    except requests.RequestException as exc:
        return {"success": False, "detail": str(exc)}




# ---------------------------------------------------------------- ollama
#
# Optional, and deliberately so. Ollama is a separate program with models of
# its own - a text model is several gigabytes on top of the twenty this app
# already asks for - and none of it is needed to make a picture. So nothing
# installs it and nothing starts it here: if it answers on 11434 the prompt
# box grows a button, and if it does not, the app is unchanged.
#
# v3 grew seven endpoints here, including a prompt enhancer with per-model
# recipes, an influencer brief generator and NSFW temperature tuning. Two are
# carried: which models exist, and turn this prompt into a better one.

OLLAMA_URL = os.environ.get("OLLAMA_URL", "http://127.0.0.1:11434")

# Preference order for the writing model, best first. Falls back to whatever
# is installed, because a machine with one model should still work.
OLLAMA_PREFERRED = ("llama3.1", "llama3", "qwen2.5", "mistral", "gemma2")


def _ollama_models() -> List[str]:
    try:
        resp = requests.get(f"{OLLAMA_URL}/api/tags", timeout=3)
        if not resp.ok:
            return []
        return [m["name"] for m in resp.json().get("models", []) if m.get("name")]
    except requests.RequestException:
        return []


def _ollama_text_model(models: Optional[List[str]] = None) -> Optional[str]:
    """The model to write with. Vision models are skipped - they answer about
    a picture rather than describing one that does not exist yet."""
    names = models if models is not None else _ollama_models()
    usable = [n for n in names if not any(v in n.lower() for v in ("llava", "vision", "-vl"))]
    for want in OLLAMA_PREFERRED:
        for name in usable:
            if name.lower().startswith(want):
                return name
    return usable[0] if usable else None


@app.get("/api/ollama/models")
async def ollama_models() -> Dict[str, Any]:
    models = _ollama_models()
    return {
        "online": bool(models),
        "models": models,
        "text_model": _ollama_text_model(models),
    }


class PromptHelpRequest(BaseModel):
    prompt: str = ""
    workflow_id: str = ""
    model: str = ""


# Two jobs, and they want different things said. An image prompt describes one
# frame; a video prompt has to carry motion, a camera, and - for MiniMax H3,
# which generates sound in the same pass - what the shot sounds like. Asking
# for one and getting the other is worse than asking for nothing.
_IMAGE_RULES = (
    "You expand short image prompts into detailed ones for a text-to-image model.\n"
    "Describe one still frame: subject, what they look like, what they are doing, "
    "the setting, the light, the lens and the mood.\n"
    "Keep every specific the user gave. Add detail, never contradict them.\n"
    "Reply with the prompt itself and nothing else - no preamble, no quotes, "
    "no explanation. Under 120 words."
)
_VIDEO_RULES = (
    "You expand short prompts into detailed ones for a text-to-video model that "
    "generates picture and sound together.\n"
    "Describe the shot over time: what moves, how the camera moves, and how it "
    "changes from the first second to the last.\n"
    "Then describe what it sounds like - the room, the sound effects, any music. "
    "The model renders audio from this, so silence about sound produces silence.\n"
    "Keep every specific the user gave. Add detail, never contradict them.\n"
    "Reply with the prompt itself and nothing else. Under 160 words."
)


@app.post("/api/ollama/prompt")
async def ollama_prompt(req: PromptHelpRequest) -> Dict[str, Any]:
    model = req.model or _ollama_text_model()
    if not model:
        raise HTTPException(status_code=503,
                            detail=f"No Ollama model answered on {OLLAMA_URL}")

    seed = (req.prompt or "").strip()
    if not seed:
        raise HTTPException(status_code=400, detail="Nothing to expand")

    # Whether this workflow makes a video is already known - the schema says
    # so, from the graph - rather than guessed from the workflow's name.
    makes_video = False
    try:
        makes_video = descriptor.describes_video(req.workflow_id)
    except Exception:
        pass

    try:
        resp = requests.post(
            f"{OLLAMA_URL}/api/chat",
            json={
                "model": model,
                "stream": False,
                "options": {"temperature": 0.6},
                "messages": [
                    {"role": "system",
                     "content": _VIDEO_RULES if makes_video else _IMAGE_RULES},
                    {"role": "user", "content": seed},
                ],
            },
            timeout=120,
        )
    except requests.RequestException as exc:
        raise HTTPException(status_code=503, detail=f"Ollama did not answer: {exc}")

    if not resp.ok:
        raise HTTPException(status_code=502, detail=f"Ollama refused: {resp.text[:200]}")

    text = ((resp.json().get("message") or {}).get("content") or "").strip()
    if not text:
        raise HTTPException(status_code=502, detail="Ollama returned nothing")
    return {"prompt": text, "model": model, "kind": "video" if makes_video else "image"}


# Last in the file, and it has to stay last. uvicorn.run blocks, so every
# route defined below this point is never registered when the app is
# started - the Ollama endpoints sat here for a while and answered 404 on a
# real launch while passing every in-process test, because importing the
# module skips this block entirely and registers them fine.
if __name__ == "__main__":
    import uvicorn

    # No reload. It doubles the process, and `object_info.cache.json` is read
    # once at import - a reloader would load several megabytes twice per edit.
    print("[FEDDA Hub v4] backend on http://127.0.0.1:8000")
    uvicorn.run(app, host="127.0.0.1", port=8000, log_level="info")
